front.v1.user.register:
  path: /registro
  controller: App\Controller\RegistrationController::registerUser

front.v1.user.login.user:
  path: /acceder
  controller: App\Controller\LoginControllerController::loginUser

front.v1.user.logout:
  path: /logout
  controller: App\Controller\LoginControllerController::logout