front.v1.user.register:
  path: /registro
  controller: App\Controller\RegistrationController::registerUser

front.v1.user.login.user:
  path: /acceder
  controller: App\Controller\LoginControllerController::loginUser

front.v1.user.logout:
  path: /logout
  controller: App\Controller\LoginControllerController::logout

front.v1.user.very.email:
  path: /panel/verify/email
  controller: App\Controller\RegistrationController::verifyUserEmail

front.v1.user.forward.email.verify:
  path: /panel/verify/email/forward
  controller: App\Controller\RegistrationController::verifyForwardUserEmail

front.v1.user.modify.account:
  path: /panel/cuenta
  controller: App\Controller\AccountUserController::accountUser

front.v1.user.delete.account:
  path: /panel/borrar-cuenta
  controller: App\Controller\AccountUserController::deleteAccountUser

front.v1.user.confirm.delete.account:
  path: /panel/borrar-cuenta/confirmar
  controller: App\Controller\AccountUserController::confirmDeleteAccountUser