front.v1.add.subdomain:
  path: /crear-subdominio
  controller: App\Controller\SubdomainController::addSubdomain

front.v1.all.subdomain:
  path: /subdominios
  controller: App\Controller\SubdomainController::listSubdomain

front.v1.edit.records.on.subdomain:
  path: /editar-subdominio/{idSubdominio}
  controller: App\Controller\SubdomainController::editSubdomain