front.v1.add.subdomain:
  path: /panel/crear-subdominio
  controller: App\Controller\SubdomainController::addSubdomain

front.v1.all.subdomain:
  path: /panel/subdominios
  controller: App\Controller\SubdomainController::listSubdomain

front.v1.edit.subdomain:
  path: /panel/editar-subdominio/{idSubdominio}
  controller: App\Controller\SubdomainController::editSubdomain

front.v1.delete.subdomain:
  path: /panel/borrar-subdominio/{idSubdominio}
  controller: App\Controller\SubdomainController::deleteSubdomain