front.v1.add.record.to.subdomain:
  path: /panel/crear-registro/{idSubdominio}
  controller: App\Controller\RecordsOfSubdomain::addRecord

front.v1.edit.record:
  path: /panel/editar-registro/{idSubdominio}/{idRecord}
  controller: App\Controller\RecordsOfSubdomain::editRecord

front.v1.delete.record:
  path: /panel/borrar-registro/{idSubdominio}/{idRecord}
  controller: App\Controller\RecordsOfSubdomain::deleteRecord